# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

strategy:
  matrix:    
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:


# Windows

- bash: |
    curl -O https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip
    curl -O https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'downloadSDL'

- powershell: |
    mkdir C:\Dev
    7z x -y "SDL2-devel-2.0.9-VC.zip" -o"C:\Dev"
    7z x -y "SDL2_mixer-devel-2.0.4-VC.zip" -o"C:\Dev"
    Rename-Item C:\Dev\SDL2_mixer-2.0.4 C:\Dev\SDL2_mixer
    Rename-Item C:\Dev\SDL2-2.0.9 C:\Dev\SDL2
  condition: eq( variables['Agent.OS'], 'Windows_NT' )   
  displayName: 'extractSDL'

- task: VSBuild@1
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  inputs:
    solution: 'vs2017\AGSWaves.sln' 
    platform: win32
    configuration: Release

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Windows_NT' )   
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/vs2017/Release'
    contents: 'AGSWaves.dll'
    targetFolder: $(Build.ArtifactStagingDirectory)

- bash: |
    echo "##vso[task.setvariable variable=tagname]$(git describe --tags $(git rev-list --tags --max-count=1))"
# Upload to Github Release
- task: GithubRelease@0 
  displayName: 'Create GitHub Release'  
  inputs:
    tagSource: 'auto'
    tag: $(tagname)
    assetUploadMode: 'replace' 
    action: 'edit' 
    gitHubConnection: agswaves
    repositoryName: Dualnames1/AGSWaves          
    assets: |
         $(Build.ArtifactStagingDirectory)/*.dll
         
